function getScenarioConfig() {
    return {
        meta: {
            title: "第三章第二幕",
            author: "六个基米哈一天"
        },
        assets: {
            background: "backgrounds/scene3.2.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "弗雷德里克・克雷伯格", text: "我叫弗雷德里克・克雷伯格", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "是个作曲家", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我出生在一个著名的音乐世家", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我本该有一个双胞胎弟弟", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "但弟弟没能成功降生", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "只有我孤独的来到了这个世界", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "由于我出生时身上奇怪的红色印记", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "家族的教堂拒绝为我洗礼", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "而我脑中时不时传来的奇怪的声音", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "更是让我的精神备受煎熬", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我偶发的精神亢奋", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "被诊断为一种儿童精神障碍", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "一般会在成年后自愈", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "直到有一次参加父亲的音乐会", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "在听到如同天籁般的音乐后", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我仿佛在空气中看到了闪着金光的乐章", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "乐章不断传播着我的能量", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "它将我推向殿堂之上", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "它们能让我校正自己思维中的杂音", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "变得安静", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "于是我爱上了音乐带给我的感觉", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "在首次参加家族交响乐的演奏当中", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "压轴出场的我表现尤为出色", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "在空气中我嗅到才华散发的芬芳", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "最好的教育加上音乐的天赋还有出色的容貌", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "所以这次首秀让我脱颖而出", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "只可惜成年后", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "人们只是谈论我的样貌和关心我的感情生活", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "没有人欣赏我的才华", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "一夜之间", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我从众星捧月的天之骄子 沦为了人们八卦的谈资", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "在人才济济的克雷伯格家族", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "为了脱颖而出", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我每天都需要在度的压力下创作", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "很快我的灵感枯竭了", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "由于人们对我的期望过高", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "而我创作出的作品又很不 “克雷伯格”", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "于是我被排挤到了家族的边缘", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "而我的父亲对我也十分失望", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "他总是用难听的话刺激我", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "“弗雷德里克，家族不需要你这样的人”", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我曾以为我会和家族的其他人一样", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "受到缪斯女神的庇护", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "只可惜我的家族不再为我提供人脉和金钱的支持", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "而为了维持相对体面的生活表象", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我不得不凭借皮囊和优雅的言谈举止", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "游走于上层社会", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "为她们弹奏", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "供她们赏乐", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我为这种生活感到羞愧", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "却也没有办法不这么做", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "当我在弹琴时", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我总会看到另一个世界中", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我本该拥有的景象", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "在熠熠闪光的舞台上自由，快乐，满足", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "而如今我的琴键早已被埋葬了", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "这个世界逐渐变得荒唐", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "你相信吗", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "好在我的音乐受到了小说家奥尔菲斯的赏识", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "是的", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "在这个古典音乐的时代", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "终于有人理解了我的浪漫主义", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "他资助我举办了一场个人独奏音乐会", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "演奏的曲目为德罗斯夫人创作的乐曲《重逢之时》", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "后来我受到了尼古拉斯・奥松维尔夫人的邀请", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "前往她巴黎的歌剧院作为艺术顾问", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "于是我坐上了从维也纳前往巴黎的列车", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "去了巴黎以后", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我依然没有放弃创作", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我时常会往家里寄家书", sprite: "characters/.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "每一封都附带一叠乐谱", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我希望父亲和家族能看到我的作品", sprite: "characters/3..png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "接纳我的作品", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "但最终乐谱和信件都会被随意丢在废纸箱里", sprite: "characters/3.2.png", side: "" },
                { name: "弗雷德里克・克雷伯格", text: "歌剧院的大火又使我失去了工作", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・雷伯格", text: "不过好在奥尔菲斯先生帮助了我", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "让我在欧利蒂丝庄园生活", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "作为回报", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "我作为第二个记录者", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "帮助他完成庄园实验", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "一份轻松的工作", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "欣赏我的才华的老板", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "免费的食宿", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "还有随便我使用的钢琴", sprite: "characters/3.2.png", side: "right" },
                { name: "弗雷德里克・克雷伯格", text: "何乐而不为呢", sprite: "characters/3.2.png", side: "right" }
            ],
            en: [
                { name: "Frederick Kreiberg", text: "My name is Frederick Kreiberg", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "and I am a composer.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I was born into a renowned musical family.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I was supposed to have a twin brother,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "but he didn’t survive birth—", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "only I came into this world alone.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Because of the strange red mark on my body at birth,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "the family’s church refused to baptize me.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "And the strange voices that occasionally echoed in my mind", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "tormented my mind even more.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "My occasional episodes of mental excitement", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "were diagnosed as a childhood mental disorder,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "one that typically resolves on its own after adulthood.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Until one time, when I attended my father’s concert—", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "after hearing music as beautiful as the sound of heaven—", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I seemed to see golden musical notes shimmering in the air.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "The notes kept channeling my energy,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "lifting me up to a sacred realm.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "They allowed me to filter out the noise in my thoughts", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "and find calm.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Thus, I fell in love with the feeling that music brought me.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "During my first performance with the family symphony orchestra,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I performed exceptionally well as the finale act.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "In the air, I could smell the fragrance of talent.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "With the best education, natural musical talent, and striking looks,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "this debut made me stand out from the crowd.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Unfortunately, after I reached adulthood,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "people only talked about my appearance and cared about my love life—", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "no one appreciated my talent.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Overnight,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I went from being a beloved prodigy adored by all to a subject of gossip.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "In the Kreiberg family, which was filled with talented people,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "to stand out,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I had to compose under extreme pressure every day.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Soon, my inspiration dried up.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Because people’s expectations of me were too high,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "and the works I created were far from “Kreiberg-style,”", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I was pushed to the margins of the family.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "My father was also deeply disappointed in me.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "He would always taunt me with harsh words:", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "“Frederick, the family doesn’t need someone like you.”", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I once thought I would, like the rest of my family,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "be blessed by the Muse.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "But unfortunately, my family no longer provided me with connections or financial support.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Yet to maintain the illusion of a decent life,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I had no choice but to rely on my looks and elegant demeanor", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "to move among high society—", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "playing the piano for them,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "providing them with entertainment.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I was ashamed of this kind of life,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "but I had no other choice.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "When I played the piano,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I would always see visions of what I was supposed to have", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "in another world:", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "free, happy, and content on a glittering stage.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "But now, my piano keys have long been buried.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "This world is becoming more absurd by the day.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Can you believe it?", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Thankfully, my music caught the attention of the novelist Orpheus.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Yes—", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "in this era of classical music,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "someone finally understood my romanticism.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "He sponsored me to hold a solo piano concert.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "The piece I performed was When We Meet Again, composed by Mrs. De Ross.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "Later, I received an invitation from Madame Nicolas Orsini-Versailles", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "to work as an art consultant at her opera house in Paris.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "So I boarded a train from Vienna to Paris.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "After arriving in Paris,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I still didn’t give up composing.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I often sent letters home,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "and each letter was accompanied by a stack of sheet music.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I hoped my father and family would see my works", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "and accept them.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "But in the end, the sheet music and letters would all be casually thrown into a trash box.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "A fire at the opera house left me unemployed once again.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "But thankfully, Mr. Orpheus helped me—", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "he let me live at Oletus Manor.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "In return,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "as the second recorder,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "I assist him with the manor experiments.", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "An easy job,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "a boss who appreciates my talent,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "free room and board,", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "and a piano I can use whenever I want—", sprite: "characters/3.2.png", side: "right" },
                { name: "Frederick Kreiberg", text: "what’s not to like?", sprite: "characters/3.2.png", side: "right" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};