function getScenarioConfig() {
    return {
        meta: {
            title: "无罪的白衣",
            author: "六个基米哈一天"
        },
        assets: {
            background: "backgrounds/scene1.11.jpg",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】",nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "莉迪亚·琼斯", text: "良知变成插在胸口的倒刺", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "拔出来会死", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "不拔出来会日夜煎熬", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我是艾米丽·黛儿", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "应该说是……莉迪亚·琼斯", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "童年殷实的家庭让我进入医学院的象牙塔", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "彼时悬壶济世像手术刀一样锐利而纯粹", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我笃信病灶分明世界秩序井然", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "离开学院后我以为能推开济世之门", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "却一脚踏进了现实的泥沼", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我拿出所有的积蓄开了一个小诊所", sprite: "characters/1..png", side: "left" },
                { name: "莉迪亚·琼斯", text: "愿医治世间病痛", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "孩子们脸烧的通红", sprite: "characters/1.11.png", side: "" },
                { name: "莉迪亚·琼斯", text: "病人枯槁的手攥着拘谨的钱袋", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "疾病折磨着这些人", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "残像使我目不忍视", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "痛呼使我耳不忍闻", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我想救他们", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "于是积蓄迅速蒸发", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "很快理想就在现实的手术台上失血", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "一个可怕的念头钻入脑海", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "那是我第一次在夜晚为一个女人进行手术", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "她走投无路眼里的恐惧比疼痛更深", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "她们的困境被视作耻辱", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我告诉自己我是在救人", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "救一个活生生的被逼到绝境的女人", sprite: ".png", side: "left" },
                { name: "莉迪亚·琼斯", text: "手术刀落下钱币入袋", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "诊所的灯似乎又能亮了", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "门外野狗撕咬垃圾袋的遮羞布的声响", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "夜夜在我灵魂回荡", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "那些未能见天日的生命", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "是我永远无法偿还的血债", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "良知变成插在胸口的倒刺", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "拔出来会死", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "不拔出来会日夜煎熬", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "去疯人院做义工", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "像丽莎贝克那样小小的惊恐的孩子", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "被粗暴地绑在冰冷的椅子上", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "驯服所谓的病症", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "这是名为净化实为虐待的治疗", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "这里的孩子需要的不是电击", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "而是拥抱耐心和爱", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "义诊结束后我写下真名署名的建议信", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我答应过要治好她", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "哪怕引火烧身", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我也希望能够帮助他们", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "黑暗中无数双婴儿的眼睛无声凝视", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "是你杀死了我们", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "像一句句诅咒", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我知道是幻觉是我的罪孽", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "报应来的飞快", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "那次助产手术入目都是猩红", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "生命在我手里流逝的这样", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "人群带着通缉令闯入", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我只能抓起手边的东西", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "在同事的掩护下仓皇逃离", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "琼斯医生的一切", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "连同那个沾满血污的济世梦想", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "彻底粉碎", sprite: "characters/1.11.png", side: "" },
                { name: "莉迪亚·琼斯", text: "我即将迷失逃亡路上时", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "一封信将我引向那个地方", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我想应该接受我的命运", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我想赎罪", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "丽莎出现了 那个疯人院的小女孩", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "现在叫艾玛", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "她的病情越发严重了", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我不愿她被骚扰", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "为她解围", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "她也认出了我", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "在这个危机四伏的庄园", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我被她视为唯一依靠", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "最亲近的对象", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "但我是违誓者", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "我债台高筑一败涂地", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "可当艾玛依赖的目光投向我寻求庇护时", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "一股仅剩的力量在我胸口挣扎复苏", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "艾玛她不该死在这里", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "这双沾满血污的手", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "或许还能拼死守护一个无辜的灵魂", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "哪怕一次", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "跟我来", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "保护她安全出去", sprite: "characters/1.11.png", side: "left"},
                { name: "莉迪亚·琼斯", text: "成了我唯一能抓住的浮木", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "这是莉迪亚·琼斯最后的机会", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "余愿尽己之能力与判断力之所", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "恪守为病家谋福之信", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "避免一切堕落害人之败行", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "愿诸神仅仅使余之生命及医术", sprite: "characters/1.11.png", side: "left" },
                { name: "莉迪亚·琼斯", text: "苟违此誓", sprite: "characters/1.11.png", side: "left" }
            ],
            en: [
                { name: "Lydia Jones", text: "My conscience became a barbed thorn lodged in my chest", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Pulling it out would kill me", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Leaving it in brought torment day and night", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I'm Emily Dyer", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I should say... I'm Lydia Jones", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "My affluent childhood allowed me to enter the ivory tower of medical school", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Back then the ideal of healing the world was as sharp and pure as a scalpel", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I firmly believed that illness was clear-cut and the world was orderly", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "After leaving the academy I thought I could push open the door to saving the world", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Instead I stepped straight into the quagmire of reality", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I used all my savings to open a clinic", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Hoping to save the world's sickness and pain", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Children's faces burned red with fever", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Patients with withered hands clutched their money pouches", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Disease tormented these people", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "The horrific sights were unbearable to see", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "The cries of pain were unbearable to hear", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I wanted save them", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "So my savings rapidly evaporated", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Soon my ideals bled out on reality's operating table", sprite: "characters/1.11.png", side: "" },
                { name: "Lydia Jones", text: "A terrible thought wormed its way into my mind", sprite: ".png", side: "left" },
                { name: "Lydia Jones", text: "That was the first time I performed surgery on a woman at night", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "She was desperate the fear in her eyes deeper than the pain", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Their plight was seen as shame", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I told myself I was saving a life", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Saving a living woman driven to the brink", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "The scalpel fell coins filled my purse", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "The clinic lights seemed able to glow again", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "The sound of stray dogs tearing at trash bags -- nature's fig leaf", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Echoed deep within my soul night after night", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Those unseen lives", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Are blood debts I can never repay", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "My conscience became a barbed thorn lodged in my chest", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Pulling it out would kill me", sprite: "characters/1.11", side: "left" },
                { name: "Lydia Jones", text: "Leaving it in brought torment day and night", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I tried volunteering at an insane asylum", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "For children like Lisa Baker small and terrified", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Brutally strapped to cold chairs", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "To tame so-called illness", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "This was treatment named purification but truly abuse", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "These children didn't need electric shocks", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "But hugs patience and love", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "After the charity work I wrote a letter of suggestions signed with my real name", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I had promised to heal her", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Even if it means bringing fire upon myself", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I still hoped to help them", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "In the darkness countless infant eyes stared silently", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "It was you who killed us", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Like whispered curses", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I knew it was hallucination my sin", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Retribution came swiftly", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "During that delivery surgery everything I saw was crimson", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Life slipped through my hands so fast", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Crowds burst in with warrant", sprite: "characters/.png", side: "left" },
                { name: "Lydia Jones", text: "I could only grab what was at hand", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "And flee in panic shielded by colleagues", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Everything of Dr Jones", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text:"Along with that bloodstained dream of healing the world", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Shattered completely", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "When I was about to be lost on the road of flight", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "A letter led me to that place", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: " thought I should accept my fate", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I wanted to atone", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Lisa appeared that little girl from the asylum", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Now called Emma", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Her condition had worsened", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I didn't want her to be harassed", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I intervened for her", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "She recognized me too", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "In this perilous manor", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "She saw me as her sole support", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Her closest confidant", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "But I am an oath-breaker", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I am deeply in debt utterly defeated", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Yet when Emma's trusting gaze turned to me seeking shelter", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "A final surge of strength struggled to life within my chest", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Emma she shouldn't die here", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "These hands stained with blood", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Might still desperately protect one innocent soul", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Even once", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Come with me", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Protecting her getting out safely", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "Became my only driftwood I could cling to", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "This was Lydia Jones's last chance", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I swear by Apollo the physician and Asclepius and Hygieia and Panacea and all the gods and goddesses that according to my ability and judgement", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I will keep Oath and this covenant", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "I will abstain from all intentional wrong-doing and harm", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "May the gods grant me life and the practice of my art with honor", sprite: "characters/1.11.png", side: "left" },
                { name: "Lydia Jones", text: "should I break this oath, let me be forsaken", sprite: "characters/1.11.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};