function getScenarioConfig() {
    return {
        meta: {
            title: "第一章第二幕", 
            author: "六个基米哈一天"
        },
        assets: {
            background: "backgrounds/scene1.2.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】",nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue" }
        },
        dialogues: {
            zh: [
                { name: "艾玛・伍兹", text: "时光是回忆的最佳滤镜", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "在一切还未发生之前", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我是艾玛・伍兹", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "曾经有一个被遗忘的名字 —— 丽莎・贝克", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "那个名字承载着我几乎忘却的记忆", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "一段我想拼尽全力回忆", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "另一段我却不愿再想起", sprite: "characters/1.2.png", side: "" },
                { name: "艾玛・伍兹", text: "我曾经也是个幸福快乐的小女孩", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我喜欢父亲亲自为我制作的玩偶", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "喜欢母亲睡前在我耳边的呼唤", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "然而一切的一切从爸爸认识那个年轻的叔叔之后就开始变了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "他总是带着鲜花来到我们家", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "爸爸和妈妈开始吵架", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "妈妈走了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "那天晚上我没有睡着", sprite:"characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "她留下的最后一句话是", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "“对不起。”", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "爸爸喝了太多酒", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "开始从家里东西出去卖", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "有时候会有陌生人闯进家里搬东西", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我不知道发生了什么", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "但这感觉很", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "糟、糕、", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "爸爸把我送到了孤儿院里", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我知道", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "他太忙了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "但是他再没来过", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "爸爸也不要我了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "孤儿院变成了疯人院", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我还是那个没有家的孩子", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "他们用叫做治疗的电击折磨我", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我只好用幻想来抵抗这世界的恶意", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "幻想侵蚀了我的记忆", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "缺失的安全感变成了情感的依赖", sprite: "characters/1.2.png", side: "left"},
                { name: "艾玛・伍兹", text: "她说她会拯救我", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "但是那个医生再也没回来", sprite: "characters/1.2.png", side: "left" },
                {name: "艾玛・伍兹", text: "听说她害死了一个女人", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "是怀着我的妹妹的妈妈", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我试图从暗无天日的生活中逃脱", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "但那位先生却又把我抓了回来", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "自由来之不易", sprite: "characters/.png", side: "" },
                { name: "艾玛・伍兹", text: "转瞬即逝", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "幸运的是我收到了那封来信", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "信中有一枝蓟花", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我知道我的机会来了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "那安静的庄园让我心慌", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "皮尔森先生对我纠缠般地求爱", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "莱利先生的行踪诡异心怀鬼胎", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我只能向稻草人先生诉说", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "好在艾米丽愿意保护我", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "倾听我的诉说", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "她温柔善良", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "她给予我怀抱", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "像我的母亲", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "艾米丽...", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我的天使、我的良药", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "看着她的眼睛就能让我平静", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "很像曾经的那位医生", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我记得她说过", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "“莉迪亚会一直支持丽莎”", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "“直到永远”", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "皮尔森先生失踪了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "稻草人先生说话了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我很高兴", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "他也变得暖暖的", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我把他带到了游戏的工厂", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "烧掉了他", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "希望艾丽能看到我的信号", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "游戏中的那个怪人没有抓住我", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "而是看着我离开", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "他看起来那样熟悉和悲伤", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我好像听到他在我身后叫了一个陌生的名字", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "丽莎……", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "不知道为什么", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "写下这个名字让我双目刺痛", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "“你梦见了什么”", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "“家”", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "“哦……”", sprite: "characters/1.2.png", side: "left"},
                { name: "艾玛・伍兹", text: "“那是什么感觉”", sprite: "characters/1.", side: "left" },
                { name: "艾玛・伍兹", text: "“我不知道……”", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "那时候的溪水那么清澈", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "还倒映着你的影子", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "冷夜高墙下", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我幻想自己褪去了痛苦的躯壳", sprite: "characters/1.2.png", side: "left" },
                { name:"艾玛・伍兹", text: "在月光中自由穿行", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "度日如年的病院里", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "那个曾经被父亲像小公主一样宠着的幸福女孩儿现在在何处", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "妈妈，我想你了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "我想知道驱使情感涌动的一切过往", sprite: ".png", side: "left" },
                { name: "艾玛・伍兹", text: "我想听听你的声音", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "想你摸着我的发顶告诉我", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "关于爸爸、关于你、关于我们家", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "对了", sprite: "characters/1.2.png", side: "left" },
                { name: "艾玛・伍兹", text: "蓟花的花语是复仇", sprite: "characters/1.2.png", side: "left" }
            ],
            en: [
                { name: "Emma Woods", text: "Time is the finest filter for memories.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Before anything ever happened,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I was Emma Woods.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Once, there was a forgotten name—Lisa Beck.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "That name carries memories I’ve nearly lost,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "one part I’m desperate to piece together,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "and the other part I never want to recall again.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I used to be a happy little girl too.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I loved the dolls my father made for me with his own hands,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "and the whispers my mother spoke in my ear before bed.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "But everything changed the day Dad met that young uncle.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "He always came to our house with bouquets of flowers,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "and Dad and Mom started fighting.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Mom left.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I didn’t sleep that night.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "The last words she left were,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "“I’m sorry.”", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Dad drank too much,", sprite: "characters/1.2.png", side:"left" },
                { name: "Emma Woods", text: "and started taking things from home to sell.", sprite: "characters/1.2", side: "left" },
                { name: "Emma Woods", text: "Sometimes strangers would burst in and carry things away.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I didn’t know what was happening,", sprite: "characters/1.2.png", side: "left"},
                { name: "Emma Woods", text: "but it felt so—", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "awful, terrible.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Dad sent me to an orphanage.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I told myself,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "he was just too busy.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "But he never came back.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Dad didn’t want me anymore either.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "The orphanage turned into a asylum.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I was still the child without a home.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "They tortured me with electric shocks they called “treatment.”", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "So I used fantasies to fight off the world’s cruelty.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Fantasies ate away at my memories,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "and the security I lacked turned into emotional dependence.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "She said she would save me,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "but that doctor never came back.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I heard she’d killed a woman—", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: " mother who was carrying my little sister.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I tried to escape that endless darkness,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "but that gentleman caught me and brought me back.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Freedom was hard to come by,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "and gone in the blink of an eye.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Luckily, I received that letter.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Inside was a thistle.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I knew my chance had come.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "That quiet manor filled me with unease.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Mr. Pearson pestered me with his advances,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Mr. Riley acted suspiciously, harboring ill intentions.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I could only pour my heart out to Mr. Scarecrow.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Thankfully, Emily was willing to protect me,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "to listen to my stories.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "She was gentle and kind,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "and she held me in her arms—", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "just like my mother used to.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Emily...", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "My angel, my healing.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Just looking into her eyes calmed me down,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "much like that doctor once did.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I remember she said,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "“Lydia will always stand by Lisa,”", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "“forever.”", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Mr. Pearson disappeared.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Mr.crow spoke.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I was so happy—", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "he’d grown warm too.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I took him to the game’s factory,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "and burned him.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I hoped Emily would see my signal.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "That strange man in the game didn’t catch me;", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "he just watched me leave.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "He looked so familiar, so sad.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I thought I heard him call a strange name behind me—", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Lisa...", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I don’t know why,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "but writing this name stings my eyes.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "“What did you dream about?”", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "“Home.”", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "“Oh...”", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "“What does it feel like?”", sprite: "characters/1.2.png", side: "left" },
                { name: " Woods", text: "“I don’t know...”", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Back then, the stream was so clear,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "still reflecting your silhouette.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Beneath the high walls on cold nights,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I fantasized about shedding this body of pain,", sprite: "characters/1.2.png", side:"left" },
                { name: "Emma Woods", text: "gliding freely in the moonlight.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "In that asylum where days felt like years,", sprite: "characters/1.2.png", side: "left"},
                { name: "Emma Woods", text: "where is the happy little girl who was once doted on like a princess by her father?", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Mom, I miss you.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I want to know all the past that stirs these feelings,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "I want to hear your voice,", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "want you to stroke my hair and tell me—", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "about Dad, about you, about our home.", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "Oh, and one more thing:", sprite: "characters/1.2.png", side: "left" },
                { name: "Emma Woods", text: "the thistle’s language is revenge.", sprite: "characters/1.2.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};