function getScenarioConfig() {
    return {
        meta: {
            title: "第一章第四幕",
            author: "第五人格团队"
        },
        assets: {
            background: "backgrounds/scene1.4.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[ End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "里奥・贝克", text: "我是里奥・贝克", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "一个失败的男人", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我曾经拥有着一个幸福美好的家庭", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我经营着一个纺织厂", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "过着平凡的生活", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我温婉的妻子玛莎精明能干", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "她走访过很多市集，寻找改善纺织厂的方法", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "许多方案都是那样令人拍案称奇", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "这一切平凡的美好却又因为我的失败和愚蠢离我远去", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "玛莎怀上了我们的丽莎", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text:"我担忧她的身体状况", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "更想要像一个真正的男人一样", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "独自承担并发展事业", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我的愚蠢将 \"父亲与丈夫的职责\" 归结为争取更好的物质条件", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "也正是我的这份愚蠢与逞能", sprite: "characters/1.4.png", side: "left" },
                { name: "奥・贝克", text: "让我在莱利的诱导下接手了那座负债累累的军工厂", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "那个律师巧舌如簧而又谎话连篇", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我却把他当做朋友", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "相信了他的建议", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "军工厂是没有未来的", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "玛莎无数次劝告过我", sprite: "characters/.png", side: "left" },
                { name: "里奥・贝克", text: "然而我却在错误的道路上执迷不悟", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我每天在工厂的繁忙之中拖着满身肮脏回家", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "没有时间陪伴我最爱的家人", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "但是也没能给这个家庭带来更好的生活", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我那愚蠢的男性自尊", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "让我在家庭和事业中都一败涂地", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我跟玛莎之间的隔阂越来越深", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "直到那个夜晚她留下了一封信悄然离开，再也没有回来", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "就这样，我的金钱、我的事业、我的家庭", sprite: "characters/1.4.png", side: "left"},
                { name: "里奥・贝克", text: "都被那个骗子弄得支离破碎", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我只好把丽莎接到了军工厂", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "丽莎爬到堆着的货箱上，我会亲自把她扛到地上", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我害怕她摔倒", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "但是又喜欢这样和她玩闹", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "可是有一次，丽莎反复爬上去", sprite:"characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "又让我把她背下来", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我差点因为这个被她弄伤", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "那是我唯一一次对丽莎发火", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "也是最后悔的一次", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我害怕自己受伤后不能工作，无法偿还债务，也无法让丽莎生活得更好", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "但是当丽莎哭着告诉我", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "\"是因为妈妈走了，", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "爸爸抱我的时间也变短了\"", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "这句话让我湿了眼眶", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我道歉了很多次", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "即便如此，我也无数次感受到懊恼和忏悔", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "都是因为我的，没能有更多的时间陪伴丽莎", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "没能让丽莎拥有一个完整的家庭和更幸福的生活", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "然而我的经济越发拮据", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我只能用更多的时间工作来维持生活", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "没有时间照顾丽莎", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我只好将她送到了孤儿院", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我多次嘱咐神父对她好一点", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "每天给她加一瓶牛奶", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "在那个我自己都入不敷出的深冬里", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我只能这样尽可能让丽莎过得更好", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "然而这些钱又有多少落进了神父的口袋里", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "那些笨拙的恳求会不会成为一些人的谈资和笑柄", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "社会的邪恶一次次伤害我和我最挂念的年幼的丽莎", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我拼尽全力，却显得如此无力", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "\"亲爱的丽莎：", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "…… 你在孤儿院过得怎么样？", sprite: "characters/1.4.png", side: "left"},
                { name: "里奥・贝克", text: "我交代过神父每天给你加一瓶牛奶，你要记得喝。", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "天越来越冷了，你晚上睡觉总喜欢踢被子，虽然可能是随我，但这毛病不好，一定要改掉。", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "还有你母亲，她选择离开这件事和你一点关系都没有，你不是没人要的孩子……", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "孩子，我要离开这里了，想看看有没有新的赚钱法子，不用找我。", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "你要好好长大成人，好好活下去。", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "以后你一定要记住，不要轻信任何人，要为自己活下去，太多的善意并不能给你带来好运。爸爸花了太长时间才学会这些，但我知道，我的丽莎一向聪明，知道该怎么做。", sprite: "characters/.png", side: "left" },
                { name: "里奥・贝克", text: "后，还记得我们经常玩的烧草人游戏吗？不久，那座被诅咒的工厂都会是你的玩具。", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "这大概是你无能的父亲唯一能为你做的。", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "………………\"", sprite: "characters/1.", side: "left" },
                { name: "里奥・贝克", text: "我总是不善言辞", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "就像我不懂如何跟玛莎沟通", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "也不懂如何向我的丽莎表达爱意", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "我就是这样一个不合格的丈夫", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "一个不称职的父亲", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "就这样吧", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "希望这场大火带我离开这处处与我作对的人间", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "希望丽莎看到这封信的时候，能知道我一直爱着她", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "希望这份保险的赔偿金能让丽莎独自过得更好", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "这是我能为你做的最后一件事了", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "有谁知道呢，那封充满爱意的信没能寄出，连同着那份以丽莎・贝克为受益人的保险单", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "又有谁知道呢，里奥・贝克最爱的妻子因为梅斯默医生的精神药品，在生产时意外死去，连同着莉迪亚・琼斯医生的生活也因此颠沛流离", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "可是谁能想到里奥・贝克没能在那场大火中完全死去，而是被人带到了圣心医院，被制作成了一个无情的杀戮机器。可这个机器有一个致命的程序问题，每年的12月21日会表现出异常的亢奋——那是丽莎・贝克的生日", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "然而在那场庄园游戏中，这台机器违背了规定，拒绝攻击玩家艾玛・伍兹，因而在那次实验结束后被销毁", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "即使变成了不人不鬼的杀戮机器，里奥・贝克依然保留着保护丽莎的本能。然而失去记忆的艾玛・伍兹一次次思索这个怪人和自己的关系，却再也没能想起自己最爱的父亲", sprite: "characters/1.4.png", side: "left" },
                { name: "里奥・贝克", text: "可是悲剧啊，又能责怪谁呢", sprite: "characters/1.4.png", side: "left" }
            ],
            en: [
                { name: "Leo Beck", text: "I am Leo Beck.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "A failed man.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I once had a happy and wonderful family.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I ran a textile factory,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "living an ordinary life.", sprite: "characters/1.4.png", side: "" },
                { name: "Leo Beck", text: "My gentle wife Martha was smart and capable.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "She visited numerous markets to find ways to improve the textile factory.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Many of her plans were truly amazing.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Yet all this ordinary happiness slipped away from me because of my failure and foolishness.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Martha was pregnant with our Lisa.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I worried about her health,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "and more than anything, I wanted to be a true man—", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: " take on the responsibility of running and growing the business alone.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "My foolishness reduced the \"duty of a father and husband\" to striving for better material conditions.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "And it was precisely this foolishness and desire to prove myself", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "that led me to be tempted by Riley into taking over that heavily indebted arms factory.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "That lawyer was eloquent yet full of lies.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "But I treated him as a friend,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "believing his advice.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "The arms factory had no future.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Martha advised me countless times,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "yet I persisted in going down the wrong path.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Every day, I dragged my dirty body home after the busy work at the factory.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I had no time to be with my beloved family,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "yet I still couldn’t bring a better life to this family.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "My foolish male pride", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "left me a failure in both family and career.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "The rift between Martha and me grew deeper and deeper,", sprite: "characters/1.4.png", side: "left"},
                { name: "Leo Beck", text: "until that night—she left a letter, walked away quietly, and never came back.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Just like that, my money, my career, my family—", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "all were torn to pieces by that liar.", sprite: "characters/1.4.png", side:"left" },
                { name: "Leo Beck", text: "I had no choice but to take Lisa to the arms factory.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "When Lisa climbed onto the stacked crates, I would carry her down myself.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I was afraid she would fall,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "yet I enjoyed playing with her like this.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "But once, Lisa kept climbing up again and again,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "asking me to carry her down on my back.", sprite: "characters/1.4.png", side: "left" },
                { name: " Beck", text: "I almost got hurt because of her.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "That was the only time I lost my temper with Lisa,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "and the most regretful one.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I was afraid that if I got injured, I wouldn’t be able to work—unable to pay off debts or give Lisa a better life.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "But when Lisa cried and told me,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "‘It’s because Mom is gone,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "and Dad doesn’t hold me as much anymore’", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "that one sentence made my eyes well up with tears.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I apologized many times.", sprite:"characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Even so, I felt remorse and guilt countless times.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "It was all my fault for not having more time to be with Lisa,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "for failing to give her a complete family and a happier life.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Yet my financial situation became more and more difficult.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I could only work more hours to make ends meet.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "With no time to take care of Lisa,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I had to send her to an orphanage.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I told the priest many times to treat her well,", sprite: "characters/1.4.png", side: "left"},
                { name: "Leo Beck", text: "to give her an extra bottle of milk every day.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "In that deep winter when I could barely support myself,", sprite: "characters/1.4.png", side:"left" },
                { name: "Leo Beck", text: "this was the best I could do to make Lisa’s life as good as possible.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "But how much of that money ended up in the priest’s pocket?", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Would those clumsy pleas become a topic of gossip and laughter for others?", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "The evil of society hurt me and my beloved young Lisa time and time again.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I tried my best, but I seemed so powerless.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "\"Dear Lisa,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "…How are you doing at the orphanage?", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I told the priest to give you an extra bottle of milk every day—remember to drink it.", sprite: "char.png", side: "left" },
                { name: "Leo Beck", text: "It’s getting colder and colder. You always like to kick off the quilt when you sleep at night. Maybe you got that from me, but it’s not a good habit—you must get rid of it.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "And about your mother—her choice to leave has nothing to do with you. You are not a child no one wants…", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "My child, I’m leaving here. I want to see if there are new ways make money. Don’t look for me.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "You must grow up well and live a good life.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "From now on, you must remember: don’t trust anyone easily, live for yourself, and too much kindness won’t bring you good luck. It took your dad too long to learn these things, but I know my Lisa has always been smart—you’ll know what to do.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Finally, do you remember the straw man-burning game we used to play? Soon, that cursed factory will all be your toy.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "This is probably the only thing your incompetent father can do for you.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "………………\"", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I’ve never been good with words.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Just like I didn’t know how to communicate with Martha,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "nor how to express my love to my Lisa.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I am such an unqualified husband,", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "an incompetent father.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "That’s it.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I hope this fire will take me away from this world that goes against me at every turn.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I hope when Lisa reads this letter, she will know I have always loved her.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "I hope the compensation from this insurance policy will let Lisa live a better life on her own.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "This is the last thing I can do for you.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Who knows? That letter full of love was never sent, along with that insurance policy with Lisa Beck as the beneficiary.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Who else knows? Leo Beck’s dearest wife died accidentally during childbirth because of Dr. Mesmer’s psychiatric drugs—and Dr. Lydia Jones’ life was turned upside down because of this too.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "But who would have thought that Leo Beck didn’t die completely in that fire? Instead, he was taken to Sacred Heart Hospital and turned into a ruthless killing machine. Yet this machine had a fatal program flaw: it would show abnormal excitement every December 21st—that’s Lisa Beck’s birthday.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "However, in that manor game, this machine violated the rules and refused to attack the player Emma Woods. Therefore, it was destroyed after that experiment.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "Even though he became a non-human killing machine, Leo Beck still retained the instinct to protect Lisa. Yet Emma Woods, who had lost her memory, wondered about the relationship between this strange man and herself time and time again—never once remembering her dearest father.", sprite: "characters/1.4.png", side: "left" },
                { name: "Leo Beck", text: "But this tragedy—who can we blame?", sprite: "characters/1.4.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};