function getScenarioConfig() {
    return {
        meta: {
            title: "第三章第一幕",
            author: "六个基米哈一天"
        },
        assets: {
            background: "backgrounds/scene3.31.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "爱丽丝・德罗斯", text: "记得故事里的那只夜莺吗", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "你比它更勇敢", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "都说幸福的人不会来庄园", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "可我就生在庄园", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "你说我是幸福还是不幸呢", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我叫爱丽丝・德罗斯", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "是一名记者", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我的父母是一对年轻的艺术家", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "他们曾在一个偏远的地方", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "以低廉的价格买下了一座庄园", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "这本是我们一家幸福的桃花源", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "但谁知这是悲剧的开始", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "由于庄园巨大", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我的父母又十分善良", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "于是他们聘请了大量的无业游民", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "帮忙打理庄园", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "让他们能够解决温饱问题", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "其中有一对护林员的儿子叫奥菲", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "他聪明机灵", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "是我的第一个朋友", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我们非常的要好", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我总是抱着最爱的洋娃娃", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "看着他在桌上写写画画", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "而我的父母也十分喜欢他", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "并收他做了养子", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "这段幼年时光", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "成为了我这辈子最快乐的日子", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "但巨大的庄园就像一块诱人的肥肉", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "许多暴民虎视眈眈的觊觎我父母的钱财", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "于是护林员偷偷与暴民勾结", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "在奥菲 12 岁生日的那个夜晚", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "那群暴民不仅洗劫了庄园", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "还杀掉了我的父母", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "躲在床下的我亲眼目睹了父母的惨死", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "就在劫匪想我的位置一步步靠近的时候", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "奥菲跑出去引开了暴徒", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我也从此和奥菲走散", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "幸存下来得我精神受到了巨大的刺激", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "父母惨死的童年阴影", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "使我患上了严重的精神疾病", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "任何轻微的刺激都会让我无休止的尖叫", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "于是我被送进了白沙街疯人院", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "而疯人院的治疗对我的病情毫无帮助", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "性格越发孤僻的我", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "在孤儿院经常会受到其他孩子们的霸凌", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "直到 14 岁那年", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我被一位教授买走收养为实验对象并带到了墨尔本", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "为了实验教授每天都会给我喂大量的药物", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "这些药物时常导致我记忆混乱", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "噩梦不断的侵袭着我", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "但经过长期的药物治疗和物理治疗", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我似乎逐渐恢复了意识", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我想起了奥菲", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我的脑海里一直回荡着那局", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "“不要怕，我们会再见的”", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我想找出奥菲", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我想知道发生了什么", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "为了找寻真相", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "直面噩梦的我成功逃回了英国", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "成为了一名记者", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "利用职务之便调查童年悲剧和奥菲失踪的真相", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "而三周前我正调查闪金石窟矿难", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "按照原本的计划", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "本应回去采访幸存者", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "诺顿・坎贝尔", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "但动身前我失联多日的同事发来了讯息", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "她终于凭借精湛的身份伪装", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "获得了欧利蒂丝庄园的邀请函", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "为了追寻真相", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "我用这位同事的身份参加了庄园游戏", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "又回到了那个熟悉的儿时乐园", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "那座现已经臭名昭著的庄园", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "直觉告诉我", sprite: "characters/3.31.png", side: "left" },
                { name: "爱丽丝・德罗斯", text: "这或许将是我唯一的机会去亲手揭开笼罩着它的迷障", sprite: "characters/3.31.png", side: "left" }
            ],
            en: [
                { name: "Alice De Ross", text: "Do you remember the nightingale in the story?", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "You are braver than it.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "People say happy people never come to the manor,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "but I was born right here.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Do you think I'm happy or unfortunate?", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "My name is Alice De Ross,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and I'm a journalist.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "My parents were a pair of young artists.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Once, they bought a manor at a low price", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "in a remote place.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "This was supposed to be a happy paradise for our family,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "but little did we know, it was the start of a tragedy.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Because the manor was large,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and my parents were very kind-hearted,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "they hired many unemployed people", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "to help take care of the manor,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "so that these people could have enough to eat and wear.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Among them, there was a forest ranger whose son was named Orpheus.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "He was smart and quick-witted,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and he was my first friend.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "We got along extremely well.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I would always hold my favorite doll", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and watch him write and draw on the table.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "My parents also liked him very much,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and they adopted him as their foster son.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "This period of my early childhood", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "became the happiest time in my life.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "But the huge manor was like a tempting piece of meat,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and many rioters eyed my parents' wealth greedily.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "So the forest ranger secretly colluded with the rioters.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "On the night of Orpheus' 12th birthday,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "the rioters not only looted the manor,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "but also killed my parents.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Hiding under the bed, I witnessed my parents' tragic death with my own eyes.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Just as the robbers were approaching my hiding place step by step,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Orpheus ran out to distract the rioters.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Since then, I have been separated from Orpheus.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Having survived, I suffered severe mental trauma.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "The childhood shadow of my parents' tragic death", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "caused me to develop a serious mental illness.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Any slight stimulation would make me scream endlessly.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "So I was sent to the White Sand Street Asylum.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "However, the treatment there did nothing to help my condition.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "As I became more and more withdrawn,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I was often bullied by other children in the orphanage.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "It wasn't until I was 14", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "that a professor bought me, adopted me as an experimental subject, and took me to Melbourne.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "For the experiment, the professor gave me large doses of medicine every day.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "These medicines often caused my memory to be confused,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and nightmares kept haunting me.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "But after a long period of medication and physical therapy,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I seemed to gradually regain consciousness.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I thought of Orpheus,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and a sentence kept echoing in my mind:", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "\"Don't be afraid, we will meet again.\"", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I wanted to find Orpheus,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and I wanted to know what had happened.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "In order to find the truth,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I faced my nightmares head-on and successfully escaped back to the UK.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I became a journalist,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and used my position to investigate the truth behind my childhood tragedy and Orpheus' disappearance.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Three weeks ago, I was investigating the Golden Flash Grotto mine disaster.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "According to the original plan,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I was supposed to go back and interview the survivor,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "Norton Campbell.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "But before I set off, a colleague who had been out of contact for days sent me a message.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "She had finally obtained an invitation to the Oletus Manor", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "by virtue of her excellent identity disguise.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "In order to pursue the truth,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "I used this colleague's identity to participate in the manor game,", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "and returned to that familiar childhood paradise—", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "that now notorious manor.", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "My intuition tells me", sprite: "characters/3.31.png", side: "left" },
                { name: "Alice De Ross", text: "this might be my only chance to personally lift the veil of mystery shrouding it.", sprite: "characters/3.31.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};