function getScenarioConfig() {
    return {
        meta: {
            title: "第三章第四幕",
            author: "第五人格团队"
        },
        assets: {
            background: "backgrounds/scene3.4.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "梅莉・普林尼", text: "然而虫群与人类不同", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "他们不会轻易背叛", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "因为所要付出的不仅仅是一方的一些代价", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我是梅莉・普林尼", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "从擦银器的女仆到听懂蜂群低语的学者", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "不过是算准风向的迁徙", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "在我看来", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "实验室的灯光远比纱帽下的轮廓耀眼", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "为了谋生我和村里的女孩一样来到庄园做女仆", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "雕花大门如蝶翼轻颤", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我生出的向往如逐火的飞虫", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "母亲在信里叮嘱", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "“梅莉，找个好裁缝比研究蜣螂重要”", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "但他们不懂", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我的灵魂早已开始追逐虫鸣", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "白天劳作 深夜潜入书房钻研", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "只为与他谈论蚁群的秩序、蜂巢的密码", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "不久 他递来铜制钥匙", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "开启的不仅是蜂房的大门", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "还有误以为是爱情的新生", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "那段日子美得像花蜜凝成的琥珀", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "雨林里我们共骑一马", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "马鞍袋里共生蚁的碰撞胜过教堂的钟声", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "暴雨困住我们", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "他赤膊烘干我的笔记", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "水汽揉进纸页", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "字迹晕开像流泪的萤火虫", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我以为我们的灵魂能如蝴蝶共鸣", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "以为绞杀榕与宿主能够共刻年轮", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "可爱情如晨露凝于花瓣", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "在烈日下蒸为虚无", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "真相如蜂尾的毒针刺裂我的心", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我的虎头蜂毒腺数据在他论文里光滑的像他熨平的礼服没有一丝棱角", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "“你要用淑女的方式做科研”", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "他冷笑着碾碎我的抗议如踩死蝼蚁", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "带着香水味的信笺出现在他的上衣口袋", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "刺痛我的眼睛", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "“您的才华令人心动”", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我好似断翅的飞蛾跌进无光的深谷", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "夜里数着安眠药片入睡", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "报社专访集厚如拇指", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "洋洋洒洒歌颂他独闯雨林的壮举", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我的名字藏在封底", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我抚摸烫金封面", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "才明白自己和那些数据不过是他学术王冠上的宝石", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "徒留微光，无足轻重", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "分居那夜雨水浸透手稿", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "他撕毁论文如蚁群噬木", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "他说我的灵魂像腐烂的标本", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "应该锁进橱柜", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我抱着《蜂群政变论》断页离开", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "瘸腿蜘蛛仍在织网", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "八足折半网格却完美", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我才发现那些原野里的小家伙才是我永远的盟友", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "你可以拥有一切但不能同时拥有", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "他倒下时呼救声与蜂群振翅交鸣", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "似新生的序曲", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "《女王蜂》连载了27期", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "如达摩克利斯之剑悬在我的头顶", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我却只梦见举着捕虫网的少女自废墟升起", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "试剂弥漫着香气", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "虫群环绕成星云", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "此刻若重来", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我仍不会犹豫", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "蛹中的生命只有两种结局", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "要么窒息而死", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "要么撕裂束缚", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "哪怕羽化时甲壳嵌入血肉", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "门铃响动", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "我收到一份熟悉的蜜蜂标本", sprite: "characters/3.4.png", side: "left" },
                { name: "梅莉・普林尼", text: "看来腐烂的橡木桩里又孵出了新的蛀虫", sprite: "characters/3.4.png", side: "left" }
            ],
            en: [
                { name: "Meri Pliny", text: "Yet swarms of insects are different from humans—", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "they never betray easily.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "For the price to be paid is never just a small loss for one side alone.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I am Meri Pliny.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "From a maid who polished silverware to a scholar who understands the whispers of bee swarms", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "it was no more than a migration with the wind’s direction calculated.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "In my eyes,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "the light of the laboratory shines far brighter than the silhouette beneath a lady’s veil.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "To make a living, I came to the manor as a maid, just like the other girls in the village.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "The carved door trembled softly like a butterfly’s wing,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "and the longing that arose in me was like a moth drawn to fire.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "In her letter, my mother warned:", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "“Meri, finding a good tailor is more important than studying dung beetles.”", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "But they didn’t understand—", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "my soul had long been chasing the chirps of insects.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I worked during the day and sneaked into the study to research at night,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "all just to talk with him about the order of ant colonies and the code of beehives.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "Before long, he handed me a brass key.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "It unlocked not only the door to the beehive,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "but also a new life I mistakenly took for love.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "Those days were as beautiful as amber formed from condensed nectar.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "In the rainforest, we rode the same horse;", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "the rustle of symbiotic ants in the saddlebag was more precious than the chimes of a church bell.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "A heavy downpour trapped us.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "He stripped off his shirt to dry my notes,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "and the moisture seeped into the paper—", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "the ink bled like fireflies shedding tears.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I thought our souls would resonate like butterflies,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "that a strangler fig and its host would carve annual rings together.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "But love is like dew condensed on a petal—", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "it evaporates into nothingness under the scorching sun.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "The truth pierced my heart like the stinger of a bee.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "My data on the venom glands of hornets, in his paper, was as smooth as his ironed suit—no rough edges at all.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "“You should do research like a lady,”", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "he sneered, crushing my protests as if stepping on ants.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "A perfumed letter appeared in his coat pocket,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "stinging my eyes.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "“Your talent is enchanting.”", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I felt like a moth with broken wings, falling into a dark valley with no light.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I counted sleeping pills to fall asleep at night.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "The collection of newspaper interviews was as thick as a thumb,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "lavishly praising his feat of venturing into the rainforest alone.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "My name was hidden on the back cover.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I stroked the gilded cover,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "and finally realized that I, along with those data, were no more than gems on his academic crown", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "flickering with faint light, yet insignificant.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "On the night we separated, rain soaked my manuscripts.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "He tore up the papers like ants gnawing at wood.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "He said my soul was like a rotting specimen,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "that it should be locked in a cabinet.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I left with the torn pages of The Theory of Bee Swarm Coups in my arms.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "A spider with a broken leg was still weaving its web—", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "half its legs were damaged, yet its web was flawless.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "That was when I realized: those little creatures in the wilderness were my eternal allies.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "You can have everything, but not all at once.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "When he fell, his cries for help mingled with the buzz of the bee swarm—", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "like an overture to rebirth.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "The Queen Bee ran for 27 issues,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "hanging over my head like the Sword of Damocles.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "Yet all I dreamed of was a girl holding an insect net, rising from the ruins.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "The reagents filled the air with fragrance;", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "the insect swarm swirled like a nebula.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "If I could do it all over again,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I would not hesitate.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "A life in a cocoon has only two fates:", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "either suffocate to death,", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "or tear through the constraints—", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "even if the exoskeleton pierces the flesh during eclosion.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "The doorbell rang.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "I received a familiar bee specimen.", sprite: "characters/3.4.png", side: "left" },
                { name: "Meri Pliny", text: "It seems new borers have hatched from the rotten oak stump.", sprite: "characters/3.4.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};