function getScenarioConfig() {
    return {
        meta: {
            title: "第四章第三幕",
            author: "第五人格团队"
        },
        assets: {
            background: "backgrounds/scene4.3.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "噩梦", text: "我是奥尔菲斯的另一个人格", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我的诞生或许是源自内心的创伤", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "也许是源自药物的作用", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "也可能二者共同作用", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "奥尔菲斯迷失的时候就是我诞生的时候", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我诞生便拥有奥尔菲斯的全部记忆", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "与之相应的 奥尔菲斯失去了大部分的童年记忆", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "作为一个后生的保护人格", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我拥有优越的资源整合能力", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "以快的速度理解自己的处境", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "然后以一种家长的姿态谋划奥尔菲斯的未来", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我是奥尔菲斯白人格的对立面", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "在奥尔菲斯的记忆中获取了一切有利于生存的能力", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "即便是疯狂、狡诈、不择手段", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "在我看来我更在意的是 \"今我\" 而非 \"故我\"", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "一切都已改变", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "往事不可追", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我会利用当前一切可利用的", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "做出能做出的最优的决策", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "如果欧利蒂丝庄园是幽冥之地", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "那么我便是这里的王", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "在梦境与虚妄的边界", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我会提醒那个小说家不要回头", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我主导着后期的庄园游戏", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "在观测过一场场游戏后", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我产生了更多想法", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "对宗教产生了兴趣", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我的实验对象也设计了更多神学人员", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "这一切都与我背后的目的有关", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我在研究一种新的的可能性", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "有关于心理暗示、精神操控、信仰与献祭", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我企图以人类的理性去理解甚至掌控未至之境", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我与过去要解决的再也不是同样的问题了", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "1901 年调查记者爱丽丝·德罗斯假借同事的身份进入庄园", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "自从得知兰姆博士的养女奥莉·兰姆叛逃后", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我已经调查过她很久", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "为此我早有准备", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "如果说以往的游戏参赛者之间的信息差是公平的", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "都只能以自己的视角去理解事态发展", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "那么这一次的游戏便唯独只有一个人是被蒙在鼓里", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "那就是爱丽丝", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "比起实验这更像是做的一个局", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我需要亲自去确认爱丽丝的身份以及来意", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "然后再决定该如何对待她", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "如果她执意要将庄园的真相披露出去的话", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "那么我也只有一个选项", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "血缘和情义早已不再是我会考虑的因素", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "我要做的是做出最符合奥尔菲斯安全和利益的选择", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "追求真理", sprite: "characters/4.3.png", side: "left" },
                { name: "噩梦", text: "追求成功", sprite: "characters/4.3.png", side: "left" }
            ],
            en: [
                { name: "Nightmare", text: "I am Orpheus’s other personality.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "My birth may have stemmed from inner trauma,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "or perhaps from the effects of drugs,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "or maybe a combination of both.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I was born when Orpheus was lost.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "From the moment I was born, I possessed all of Orpheus’s memories;", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "correspondingly, Orpheus lost most of his childhood memories.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "As a later-formed protective personality,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I have excellent resource integration skills.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I quickly understood my situation,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "and then planned Orpheus’s future in a paternal manner.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I am the opposite of Orpheus’s \"light personality.\"", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I extracted all survival-benefiting abilities from Orpheus’s memories—", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "even madness, cunning, and unscrupulous methods.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "In my view, I care more about \"the me now\" than \"the me of the past.\"", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "Everything has changed;", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "the past can never be retrieved.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I will make use of everything available to me now,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "and make the best possible decisions I can.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "If Oletus Manor is a realm of the netherworld,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "then I am the king here.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "On the border between dreams and illusion,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I will warn that novelist not to look back.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I oversaw the later manor games.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "After observing countless games,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I had more ideas,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "and developed an interest in religion.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I also included more religious figures as my experimental subjects.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "All of this was related to my underlying goal.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I was researching a new possibility—", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "one related to psychological suggestion, mind control, faith, and sacrifice.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I sought to use human reason to understand, even control, the uncharted realm.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "The problems I needed to solve were no longer the same as those in the past.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "In 1901, the investigative journalist Alice Dross entered the manor under the alias of a colleague.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "Ever since I learned that Dr. Lamb’s adopted daughter, Ollie Lamb, had defected,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I had been investigating Alice for a long time.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "And I had long been prepared for this.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "If the information gap between participants in previous games was fair—", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "each could only understand the development of events from their own perspective,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "then in this game, there was only one person kept in the dark:", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "Alice.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "This was more of a trap than an experiment.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "I needed to personally confirm Alice’s identity and her purpose,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "and then decide how to deal with her.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "If she insisted on revealing the truth about the manor,", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "then I would have only one choice.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "Blood ties and friendship were no longer factors I would consider.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "What I needed to do was make the choice that best served Orpheus’s safety and interests.", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "Pursue the truth;", sprite: "characters/4.3.png", side: "left" },
                { name: "Nightmare", text: "pursue success.", sprite: "characters/4.3.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};