function getScenarioConfig() {
    return {
        meta: {
            title: "第三章第五幕",
            author: "第五人格团队"
        },
        assets: {
            background: "backgrounds/scene3.5.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "玛丽・安托瓦内特", text: "直到那条裙子逐渐变成了红色", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我终于明白了", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "皇后是最容易被吃掉的棋子啊", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我是玛丽・安托瓦内特", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "奥地利大公玛利亚・特蕾西亚的第十五个孩子", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "是最小的一个女儿", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "作为皇室", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我本不会成为联姻的棋子", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "所以我没有被从小严格培养", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "度过了一个无忧无虑的童年", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "保留了孩童般的天真任性", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "但也正是这天真后来成为了他们用来伤害我的利刃", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "迫于当时的政治环境", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "法国皇室向奥地利提出求婚", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "以此平息旷日持久的战争", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我的母亲女皇玛利亚・特蕾西亚亲自签下了契约", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "原计划是我的姐姐约翰娜嫁给路易十六", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "但是我的姐姐不幸死于天花", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "于是我便成了替补人选", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "母亲问预言家", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "她的女儿在法国是否会幸福", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "预言家回答", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "“你会获得你想要的，十字架为此作证”", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "然而我天性直率容易失去耐心", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "从不给讨厌的人好脸色", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "成为皇后之前", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "国王的情妇杜巴丽夫人就受足了我的蔑视", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "成为皇后之后", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我懒得理会政治家之间的勾心斗角", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "做了很多不该做的事", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "也破坏了很多皇室的规矩", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "但是这也让我乐在其中", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "皇后的权利对于我来说只是获取自己所需物品的工具", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "就像孩童喜欢玩具一样", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我喜欢把珠宝华服全部收入我的宫殿", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "在我的带领下", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "奢侈时尚的风气席卷法国贵族的生活圈", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "最奢侈的一次是修建小特里亚农宫殿", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "这是路易十六送给我的礼物", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "后来我用自己丰富的创意让宫殿越来越奢华", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "当然国库也逐渐亏空", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "在一切被欲望与恶意吞噬前", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "那只带来厄运的宝匣中", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "或许只藏着最单纯的愿望", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "然而人们对我这样穷奢欲的皇后愈发不满", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "当时法国的红衣主教得罪过我的母亲", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "为了得到原谅想要来讨好我", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "但是在母亲的指示下我没有给他任何好脸色", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "于是红衣主教找到被传是我密友的让娜", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "让娜以此骗红衣主教以我的名义分期买下昂贵的红宝石项链", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "还让一个妓女假扮我和红衣主教见面", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "因为红衣主教付不起项链的分期", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "项链商人直接找上了我", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "至此事情败露", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "红衣主教被流放", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "让娜被鞭笞后终身监禁", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "但她最后越狱逃亡英格兰", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "还写了一本书", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "《玛丽・安托瓦内特丑恶的一生》", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "书中充满了对我的诽谤", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "虽然我是无辜的", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "但是我的名声还是受到了影响", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "法国大革命期间", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "在反贵族皇室的浪潮中", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "国王和皇后成为了首要攻击目标", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "比起温和仁慈的路易十六", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "奢侈无度的我吸引了更多的仇恨", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "而这期间", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我终于丢弃享乐的天性", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "主张革命就是反叛", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "带领旧贵族抗争到底", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我真真正正的当了一次皇后", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "然而反抗终究还是失败了", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我被关进大牢", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "人们把真实的、胡编乱造的罪名通通按在我身上", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "管我叫 “赤字夫人”", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "最后我带着无数罪名被送上断头台", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "死前我不小心踩了刽子手的脚", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "“对不起，您知道，我不是故意的”", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "说完这句遗言后", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我 “臭名昭著” 的皇后一生就此落幕", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "直到我被送上刑场", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我还在苦恼自己被粗暴剪断的长发", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "直到我的白裙被染得鲜红", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我也不明白自己为何而死亡", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "他们又为什么这么厌恶我", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "为什么…… 为什么……", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "直到那条裙子逐渐变成了红色", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "我终于明白了", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "皇后是最容易被吃掉的棋子啊", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "但我带来的影响远没有结束", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "“红夫人” 这个我带来的称号变成一个可以用来诋毁女性的蔑称", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "人们想诽谤哪个女性", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "就管哪个女性叫 “红夫人”", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "可笑的肮脏的人类啊", sprite: "characters/3.5.png", side: "right" },
                { name: "玛丽・安托瓦内特", text: "可是无数个玛丽的无辜的骂名又有谁会在意呢", sprite: "characters/3.5.png", side: "right" }
            ],
            en: [
                { name: "Marie Antoinette", text: "I didn't realize until that dress gradually turned red", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Finally, I understood", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "The queen is the most vulnerable piece to be captured in the game.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I am Marie Antoinette,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "the fifteenth child of Maria Theresa, Archduchess of Austria,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "and her youngest daughter.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "As a member of the royal family,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I was never meant to be a pawn in a political marriage.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Thus, I was not raised with strict discipline from a young age.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I had a carefree childhood,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "retaining the innocence and willfulness of a child.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Yet it was this very innocence that later became a weapon they used to harm me.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Pressed by the political climate of the time,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "the French royal family proposed a marriage alliance to Austria", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "in order to end the prolonged war.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "My mother, Empress Maria Theresa, personally signed the agreement.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Initially, my sister Johanna was supposed to marry Louis XVI,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "but she unfortunately died of smallpox.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "And so, I became the replacement.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "My mother asked a soothsayer,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "\"Will my daughter be happy in France?\"", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "The soothsayer replied,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "\"You will get what you desire, and the cross shall bear witness to this.\"", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Yet by nature, I was straightforward and easily impatient.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I never bothered to hide my disdain for those I disliked.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Before becoming queen,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Madame du Barry, the king's mistress, endured no shortage of my contempt.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "After ascending to the queenship,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I had no patience for the intrigue among politicians.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I did many things I shouldn't have,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "and broke numerous royal rules,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "yet I took delight in it all.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "To me, the queen's power was merely a tool to obtain what I wanted.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Just as a child craves toys,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I loved collecting all manner of jewelry and fine clothing in my palace.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Under my influence,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "a wave of luxury and fashion swept through the lives of French nobles.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "The most extravagant endeavor was the construction of the Petit Trianon,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "a gift from Louis XVI.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Later, I used my vivid imagination to make the palace even more luxurious.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Naturally, the national treasury was gradually depleted as a result.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Before everything was devoured by desire and malice,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "inside that ill-fated treasure box,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "there might have been nothing but the purest of wishes.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Yet people grew increasingly dissatisfied with a queen as lavish as me.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "At that time, the French Cardinal had offended my mother.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Seeking forgiveness, he tried to curry favor with me,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "but following my mother's instructions, I showed him no kindness.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "So the Cardinal turned to Jeanne, who was rumored to be my close friend.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Jeanne tricked the Cardinal into purchasing an expensive ruby necklace in my name on an installment plan.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "She even had a prostitute impersonate me to meet with the Cardinal.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "When the Cardinal couldn't keep up with the installments,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "the necklace merchant went straight to me.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "And thus, the truth came to light.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "The Cardinal was exiled,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "and Jeanne was flogged and sentenced to life imprisonment.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Yet she eventually escaped from prison and fled to England,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "where she wrote a book titled", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "\"The Wicked Life of Marie Antoinette.\"", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "The book was filled with slander against me.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Though I was innocent,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "my reputation was irreparably damaged.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "During the French Revolution,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "amid the wave of anti-aristocratic and anti-royal sentiment,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "the king and queen became the primary targets of attack.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Compared to the gentle and kind Louis XVI,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I, with my excessive luxury, drew far more hatred.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Yet during this time,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I finally cast aside my hedonistic nature.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I declared that the revolution was nothing but rebellion,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "and led the old nobility in a desperate fight to the end.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "For the first time, I truly acted as a queen should.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "But in the end, the resistance failed.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I was thrown into prison.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "People piled all sorts of charges on me—both true and fabricated.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "They called me \"Madame Deficit.\"", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Finally, burdened with countless charges, I was sent to the guillotine.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Before my death, I accidentally stepped on the executioner's foot.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "\"Pardon me, sir, you know I did not do this on purpose,\" I said.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "After uttering those last words,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "my \"infamous\" life as a queen came to an end.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Even as I was led to the execution ground,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I was still upset about my hair, which had been roughly cut short.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Even as my white dress was dyed bright red,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I still didn't understand why I had to die,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "or why they hated me so deeply.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Why... why...", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "I didn't realize until that dress gradually turned red", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Finally, I understood:", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "The queen is the most vulnerable piece to be captured in the game.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Yet my influence did not end there.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "The title \"Madame Rouge\" (Lady Red), which became associated with me, turned into a derogatory term used to slander women.", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "Whenever people wanted to defame a woman,", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "they would call her \"Madame Rouge.\"", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "How ridiculous and filthy humanity is!", sprite: "characters/3.5.png", side: "right" },
                { name: "Marie Antoinette", text: "But who cares about the innocent reputations of the countless \"Maries\" wronged by this name?", sprite: "characters/3.5.png", side: "right" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};