function getScenarioConfig() {
    return {
        meta: {
            title: "第三章第三幕",
            author: "第五人格团队"
        },
        assets: {
            background: "backgrounds/scene3.3.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "诺顿・坎贝尔", text: "我曾以为人本该是善良的", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "但干瘪的钱包、痛苦的疾病和饱受折磨的灵魂", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "足以让我丢掉美好的品质", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我兢兢业业的工作", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "换来的是什么", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "一身肺病和讥讽的嘲笑", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "但有时候", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "人总能想出一些办法", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "做出一些改变", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "不是吗", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我叫诺顿・坎贝尔", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "是一名矿工", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "大家都说", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "父亲是矿工，儿子也是矿工", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "没错", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "直到我父亲去世后", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我也是这样的深信不疑", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我兢兢业业的工作", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "每天总是第一个来，最后一个离开", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我曾以为", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "只要足够努力就能挣更多的钱", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "而现实是", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我只能拿着微薄的薪水", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "每天还要忍受工友们的讥讽和嘲笑", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "只因为他们觉得我积工作", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "是为了表现自己，赢得老板的青睐", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "平时我经常会照顾父亲的老工友们", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "与他们谈心", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "悉心照顾他们的生活起居", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "这是我在压抑的生活中仅存的善良", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "直到有一天", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "父亲的一位老工友给了我一张记载着金矿的地图", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "里面标记了13个可能有金矿的地方", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "拿到地图的我兴奋不已", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我终于可以做有钱人了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "谁说父亲是矿工，儿子也是矿工", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我马上就要打破这个诅咒", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "抱歉了，本尼", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "以后我可能没法继续照看你了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "因为我还有更重要的事情要办", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "于是我再也没有去看过本尼了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我每天白天依旧忍着讥讽和嘲笑", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "表面上不动声色", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "但在晚上", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我会一个人悄悄去地图上标记的地方挖矿", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我…我要加快速度了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我的肺病越来越严重了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "这是第十二个矿了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "怎么没有…不…不可能", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "如果是这样的话", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "那么就只剩下最后一个闪金石窟了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "最后一个闪金石窟我一直没选择", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "是因为它度危险", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "新闻上说这里严禁炸矿", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "因为矿洞里面的柱子可能已经老旧", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "随时会坍塌", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "而往往越危险的地方", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "就证明那些有价值的东西会埋藏在哪里", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "但我愿意赌", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "有时候", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "人总能想出一些方法", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "做出一些改变", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "不是吗", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "于是我有了一个完美的计划", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我叫上了那群曾经欺负过我的人", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "带着一行人进入了闪金石窟", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我事先将炸药藏在矿洞四处", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "等他们挖出黄金后", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我就引爆炸弹", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "但我在引爆的那一刻十分的挣扎", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "手不停的颤抖", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "良知让我无法动手", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "可是过往的种种霸凌依旧徘徊在我脑子里", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "坚定了我最后的选择", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "只要点燃这根引线", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我就可以过上富人的生活", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我就切断了过去", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我要开始新的生活了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "最终我引爆了炸药", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "炸死了那些曾经欺负过我的人", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "什么……竟然是愚人金（注：愚人金指黄铜，外表很像金的一种矿物）", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "哈哈哈", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "我最后的希望也破灭了", sprite: "characters/3.3.png", side: "left" },
                { name: "诺顿・坎贝尔", text: "真是像了我讽刺的人生啊", sprite: "characters/3.3.png", side: "left" }
            ],
            en: [
                { name: "Norton Campbell", text: "I once believed that people were inherently kind.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Yet, an empty wallet, agonizing illness, and a tormented soul", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "were enough to strip me of all my noble qualities.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I worked diligently and conscientiously.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "What did I get in return?", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "A lung disease and nothing but sneers and mockery.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "But sometimes,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "people can always find a way", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "to make a change,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "can't they?", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "My name is Norton Campbell,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "a miner.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Everyone says,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "\"Like father, like son—if the father's a miner, the son will be too.\"", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "And that was true,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "even after my father passed away,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I still firmly believed it.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I worked diligently and conscientiously.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I was always the first to arrive and the last to leave every day.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I once thought,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "as long as I worked hard enough, I could earn more money.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "But the reality was,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I could only get a meager salary,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "and endure the sneers and mockery from my fellow workers every day—", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "simply because they thought my hard work", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "was just to show off and gain the boss's favor.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Usually, I would often take care of my father's old workmates,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "chat with them,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "and take good care of their daily lives.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "This was the last bit of kindness left in my oppressive life.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Until one day,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "one of my father's old workmates gave me a map marking gold mines,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "on which 13 places with potential gold deposits were marked.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I was overjoyed when I got the map—", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I could finally become a rich man!", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Who said \"if the father's a miner, the son will be too\"?", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I was about to break this curse.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I'm sorry, Benny.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I might not be able to take care of you anymore,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "for I have more important things to do.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "After that, I never went to see Benny again.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "During the day, I still endured the sneers and mockery,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "putting on a calm face.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "But at night,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I would secretly go to the places marked on the map to mine alone.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I... I need to speed up.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "My lung disease is getting worse and worse.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "This is the twelfth mine.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Why is there nothing here... No... That can't be.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "If that's the case,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "only the last Glimmering Gold Grotto is left.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I had been avoiding the last Glimmering Gold Grotto", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "because it was extremely dangerous.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "The news said that blasting was strictly prohibited here,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "for the pillars inside the mine might have aged,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "and could collapse at any time.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "But often, the more dangerous a place is,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "the more likely it is that valuable things are hidden there.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "But I was willing to take the risk.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Sometimes,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "people can always find a way,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "make a change,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "can't they?", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "So I came up with a perfect plan.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I invited the group of people who had bullied me before,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "and led them into the Glimmering Gold Grotto.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I had hidden explosives everywhere in the mine in advance.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Once they dug out the gold,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I would detonate the explosives.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "But at the moment of detonation, I hesitated greatly—", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "my hands wouldn't stop shaking.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "My conscience stopped me from doing it.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "But all the bullying from the past still lingered in my mind,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "strengthening my final decision.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "As long as I light this fuse,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I can live the life of a rich man.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "I can cut off my past,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "and start a new life.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "In the end, I detonated the explosives,", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "killing all those who had bullied me.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "What... It's just fool's gold (Note: Fool's gold refers to pyrite, a mineral that looks very similar to gold)!", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "Hahaha...", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "My last hope is also shattered.", sprite: "characters/3.3.png", side: "left" },
                { name: "Norton Campbell", text: "It's just like my ironic life!", sprite: "characters/3.3.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};