function getScenarioConfig() {
    return {
        meta: {
            title: "第四章第二幕",
            author: "第五人格团队"
        },
        assets: {
            background: "backgrounds/scene4.2.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "奥菲·布兰奇", text: "奥尔菲斯", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "呵呵 这不是我的真名", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "原本的名字我已经不愿再提起了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "也只有少数几个人还记得", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我曾经叫奥菲·布兰奇", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "1875 年 4 月 2 日我出生在一个工薪家庭", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "父母都是护林员", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "几年后那座臭名昭著的庄园被一对艺术家夫妇购买", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我们一家也被他们所雇佣参与到林场翻新的工作中去", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "仁慈的主人为这原本寂静萧潦的庄园带来了生机", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "这片林场成为了我的乐土", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我当时也同那个年龄段的所有男孩一样淘气贪玩", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "尤其对巴尔克先生的机关感兴趣", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "经常偷偷跟在老爷子后面观察他做实验", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "然而当时的我并非无忧无虑", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我的母亲得了一种很严重的肺痨", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "家里的大部分收入都拿去支付她的医疗费用了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "或许是同情我们家的遭遇", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "德罗斯夫妇收养我为养子", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "并给了我一个礼物", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "一支短笛和打开庄园大门的密码", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "那听起来就像夜莺的歌声", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "被收养后我的亲生父母并没有与我断联", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "相反 他们比以前更关心我了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "他们急需用钱", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "甚至要求我 \"借用\" 德罗斯家里值钱的东西", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "当时的我无法拒绝他们", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "毕竟这是我的亲生父母", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "爱丽丝·德罗斯的出生再次点亮了我的童年时光", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "她与她的家人一样有这一头灿烂的金发", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "真好 仿佛祝福着她与她善良的家人们", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "都能拥有一个如阳光般温暖的人生", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "德罗斯夫妇告诉我这是我的妹妹", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我与妹妹成为了要好的玩伴", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "一起在林场上奔跑让班恩困扰", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "探索巴尔克先生的实验室", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "妹妹会安静的听我讲故事", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "她最喜爱希腊神话", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我们便经常扮演神话故事里的情节", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "为了更好的参与过家家游戏", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我还为她制作了两个玩偶", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "一个像妹妹一个像哥哥", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "一切噩梦都始于那场生日会", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "1887 年 4 月 2 日", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "那是我的 12 岁生日", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "也是我永远忘不了的一天", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我的短笛被我的亲生父亲骗走", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "而它最终打开了庄园的大门", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "一群举着火把与枪支的流寇闯入了欧利蒂丝庄园", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "杀死了德罗斯夫妇", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我和妹妹目睹了这一切", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我在那群暴民中看到了我的亲生父亲", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "那天后来发生了什么我已经记不清了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "尽管那是我每次噩梦的固定环节", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "但经过反复的回忆已经被扭曲太多次再也不是原貌了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "庄园被变卖", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我被送到了孤儿院与妹妹彻底失散", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "至此我的童年提前结束了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "刚开始到达孤儿院的时候我的精神很恍惚", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "整体沉浸在那日的噩梦幻影中", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "等我回过神来才想到当年事件的疑点", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "而这起事件也被警方定性为悬案", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "作为一个孩子我能了解到的事情实际太少", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我不知道爱丽丝的下落不知道庄园的下场也不知道引发那起事件的原因", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "因此只能存下心中的疑惑", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "先让自己能够在社会上活下来再去追查当年的疑案", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "写作是我的天赋所在", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "在孤儿院中为了逃避过去的阴影与虚伪的社交", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我整日沉浸在创作中", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "随着我慢慢长大从孤儿的身份独立出来以后", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "便在社会上靠自己的本事赚到了不错的钱", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "使用小说家这一身份活动", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "既然能够维持自己的生活了就开始寻找妹妹爱丽丝的下落", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "1894 年我查到爱丽丝在迈尔西孤儿院", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "12 月 23 日我第一次像迈尔西孤儿院院长提出的领养申请被拒绝了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "信中关于爱丽丝当前处境的描述让我格外揪心", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "她依然在遭受当年的噩梦的侵扰", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我立即给孤儿院捐了一大笔钱", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "希望能为爱丽丝配置更好的环境", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "然而当我再次提出探视申请时却依旧被拒绝了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "这一次的信中提到有一位大人物对爱丽丝动了恻隐之心然后便带走了她", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "9 月 13 日对我来说是一个特殊的日子", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "一场大火焚烧了迈尔西孤儿院", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "也再一次毁灭了我的愿望", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "她已经不在那里了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我曾有设想把她从孤儿院里带出来", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "成为父女我们就能重聚", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我就能弥补她", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "可是她再一次离开了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "女儿的愿望彻底破灭", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "但我却从此经常能够看到一个幻影", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "一个金发白裙的小女孩", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "1895 年我 20 岁", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我加入了位于地中海塞浦路斯的一个药物研发项目小组", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "是带走爱丽丝的医学博士墨尔本勋爵·维尔赫姆·兰姆带领的组织", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "在这里我认识了两个同僚：山姆·波本和罗伊", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我们三个人的研究方向并不相同", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我研制出来的药剂名为七弦琴", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "只需要少的剂量就可以让受试者陷入昏迷", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "山姆的药剂为塞壬之歌", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "药效是致幻和放大恐惧", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "罗伊的药剂是摩涅莫绪涅后被改名为狄俄尼索斯", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "可以让使用者忘记一段记忆", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我们三个人只是看上去志同道合罢了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "实际上是各怀鬼胎", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "尤其是我在离开孤儿院之后一直在调查当年灭门案的真相", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "在灭门案发生半年前", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我的亲生父亲老布兰奇因无力支付妻子的医疗费用向巴利尔家族借了一笔巨款", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "后又因无力偿还借贷与贵族达成交易", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "伙同在庄园周边偷猎的流寇", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "骗走了我的短笛将德罗斯夫妇残忍杀害", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "他们并非为了抢劫庄园里的财物", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "而是为了完成雇主下达的任务", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "事件过后流寇分得了酬金", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "庄园里的财务被德罗斯的亲戚变卖", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "两个孩子被送往不同的孤儿院", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "警察调查该事件屡屡受阻最终定性为悬案", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "原来这一切都笼罩在一个蓄意谋杀的阴谋之下", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "在我查到这些线索的时候", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我的亲生父母早已去世多年", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "而当年的借贷人正因为其他的犯罪记录在监狱中服刑", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "巴利尔伯爵是个无往不利的投机者", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "哪里能获益哪里就有他", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "他多对兰姆博士的地中海项目亦有投资", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "购买了地中海发展债券", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "而后他似乎看中了我的某种特征", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "又与我达成协议", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "将债券借给了我", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "随着债券一起给我的", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "还有一本《奥菲欧》或是在暗示着什么", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "总之这笔交易让当时不算大富大贵的我可以直接获取地中海项目的部分收益", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "是一笔超值的买卖", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "说回药剂研发实验也并非一帆风顺", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "不少原材料获取困难、运输周期长、合作方不稳定、培养条件刁钻", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "这些因素都导致研发时间会被无限拉长", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "这可不是我所期待的结果", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我的妹妹还在受苦", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我不能让她等太久", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "为了管控工期确保药物能够尽快投入使用", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我在诸多流程上不得不亲力亲为", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "当时欧利蒂丝庄园还在马努斯手下", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "夫人玛丽·克雷伯格在赛马场自杀正闹得沸沸扬扬", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "克雷伯格赛马场从此蒙上了一层不祥的色彩", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "但赛马的比赛依旧没有停止", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我利用了那段时期的风波", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我的第一目的自然是将马努斯从庄园赶走", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "当然我也带了点对于当年那笔借贷的报复心理", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我盯上了那场巴利尔伯爵为扶持家族中的赛马新秀西蒙·巴利尔而在克雷伯格赛马场举行的赛马会", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我制造了一点意外", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "名驹塞恩勒斯在比赛中发了狂冲出赛道造成了大规模踩踏伤亡事件", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "它引起的骚乱也令当时在场的骑师西蒙摔下了马导致终生瘫痪", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "而马努斯也陷入了巨额债务风波", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "马努斯一方面难以忘怀亡妻的逝世", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "一方面又要面临无力偿还的高额债务", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "不出所料的疯了从此不知所踪", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "庄园也再次被债主们挂上了出售的标牌", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "1898 年药剂完成一期研发", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "即可投入二期临床试验", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我也靠之前的暗中交易获得了一大笔金钱", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "实际已然成熟", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "此刻便是重返庄园之时", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我隐姓埋名买下了欧利蒂丝庄园", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "成为了德罗斯男爵", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "并买回了当年被亲戚们变卖的收藏品", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "班恩和巴尔克还在这里", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "终于等到了故人回归", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我把这一切都找回来了", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "欧丽蒂斯正如彼时童年的记忆一般死灰复燃", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "同年我出版的小说一炮而红", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "我获得了一笔丰厚的版税和光荣的名声", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "在我成名后我立即利用自己财富和名声的优势结交友人", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "为后续源源不断的庄园游戏参与者埋下了伏笔", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "同时我也有一批亲信", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "管家、罗伊等人会为我搜集参赛者的资料帮助布局实验内容", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "来支撑这一场又一场实验的顺利举行", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "这一切从不是单方面的迫害", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "事实上我对待参赛者只是对症下药而已", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "也只有找到最合适的药品", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "才能治好爱丽丝的心病", sprite: "characters/4.2.png", side: "left" },
                { name: "奥菲·布兰奇", text: "才能让我唯一的家人回到我身边", sprite: "characters/4.2.png", side: "left" }
            ],
            en: [
                { name: "Orpheus Blanche", text: "Orpheus—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "oh, that’s not my real name.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I no longer wish to speak of my original name,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and only a handful of people still remember it.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Once, I was called Orpheus Blanche.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I was born into a working-class family on April 2, 1875.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My parents were both forest rangers.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "A few years later, that notorious manor was bought by a couple of artists.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Our family was hired by them to take part in the renovation of the forest farm.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The kind masters breathed life into this once quiet and desolate manor.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "This forest farm became my paradise.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Back then, I was as naughty and playful as any boy my age,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and I was especially fascinated by Mr. Balke’s mechanisms.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I would often sneak behind the old man to watch him conduct his experiments.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Yet I was not carefree back then.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My mother suffered from a severe case of tuberculosis.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Most of the family’s income went to covering her medical bills.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Perhaps out of sympathy for our family’s plight,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "the Dross couple adopted me as their foster son,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and gave me a gift:", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "a piccolo, and the password to open the manor’s gates—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "it sounded just like the song of a nightingale.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "After being adopted, my biological parents did not cut off contact with me.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "On the contrary, they cared about me more than ever.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "But they were desperate for money,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and even asked me to \"borrow\" valuable items from the Dross household.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I couldn’t refuse them back then—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "they were my biological parents, after all.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The birth of Alice Dross lit up my childhood from that moment on.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Like her family, she had a head of bright golden hair.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "It was so lovely, as if it were a blessing—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "a wish that she and her kind family would all have a life as warm as the sun.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The Dross couple told me she was my younger sister.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "We became close playmates.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "We ran through the forest farm together, much to Bane’s annoyance;", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "we explored Mr. Balke’s laboratory.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My sister would listen quietly as I told her stories,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and her favorite were Greek myths.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "So we would often act out scenes from those myths.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "To make our make-believe games more vivid,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I made two dolls for her:", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "one that looked like her, and one that looked like me.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "All nightmares began with that birthday party—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "April 2, 1887.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "It was my 12th birthday,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and a day I would never forget.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My biological father tricked me into giving him my piccolo,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and it was that piccolo that finally opened the manor’s gates.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "A band of brigands wielding torches and guns broke into Oletus Manor,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and killed the Dross couple.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My sister and I witnessed it all.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Among the mob, I saw my biological father.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I can no longer remember what happened later that day—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "even though it’s a constant part of my nightmares.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "But after being replayed so many times in my memories, it has become so distorted that it’s no longer the truth.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The manor was sold off,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and I was sent to an orphanage, separated from my sister forever.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "From that moment on, my childhood ended prematurely.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "When I first arrived at the orphanage, my mind was in a daze.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I was lost in the phantoms of that day’s nightmare.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "It wasn’t until I came to my senses that I began to notice the doubts surrounding that incident.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Yet the police classified the case as unsolved.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "As a child, there was very little I could find out.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I didn’t know where Alice was, what had become of the manor, or what had caused the incident.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "So I could only hold onto the doubts in my heart,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and focus on surviving in this world before I could investigate that old case.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Writing was my talent.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "In the orphanage, to escape the shadows of the past and the hypocrisy of social interactions,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I immersed myself in writing all day long.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "As I grew up and became independent from the orphanage,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I made a decent living in society with my own skills,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "working under the identity of a novelist.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Once I could support myself, I began searching for my sister Alice.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "In 1894, I found out she was at Mercy Orphanage.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "On December 23, my first application to adopt her, submitted to the director of Mercy Orphanage, was rejected.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The description of Alice’s current situation in the rejection letter tore at my heart.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "She was still tormented by the nightmares from that year.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I immediately donated a large sum of money to the orphanage,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "hoping to provide Alice with a better environment.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Yet when I applied for a visit again, I was still rejected.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "This time, the letter mentioned that a prominent figure had taken pity on Alice and taken her away.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "September 13 was a special day for me—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "a fire burned down Mercy Orphanage,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and once again, my hopes were destroyed.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "She was no longer there.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I had dreamed of taking her out of the orphanage,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "of us becoming like father and daughter so we could be reunited,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "so I could make up for what she’d lost.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "But she was gone again.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My wish to have her as my \"daughter\" was completely shattered.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Yet from that day on, I often saw a vision:", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "a little girl with golden hair and a white dress.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "In 1895, I turned 20.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I joined a drug research and development team located in Cyprus, the Mediterranean.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "It was an organization led by Lord Melbourne Wilhelm Lamb, the medical doctor who had taken Alice away.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Here, I met two of my colleagues: Sam Bourbon and Roy.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The three of us had different research focuses.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The drug I developed was called Lyre—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "a tiny dose was enough to put the subject into a coma.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Sam’s drug was called Siren’s Song;", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "its effect was to induce hallucinations and amplify fear.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Roy’s drug was originally called Mnemosyne, later renamed Dionysus—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "it could make the user forget a specific memory.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The three of us only seemed to share the same goals;", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "in truth, each of us had our own hidden agendas.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "In particular, ever since I left the orphanage, I had been investigating the truth behind the massacre.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Six months before the massacre,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My biological father, Old Blanche, had borrowed a large sum of money from the Barriere family because he couldn’t afford his wife’s medical bills.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Later, unable to repay the debt, he made a deal with the nobility:", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "teaming up with poachers who lurked around the manor,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "he tricked me out of my piccolo and cruelly killed the Dross couple.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "They weren’t after the manor’s treasures;", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "they were only carrying out a task assigned by their employer.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "After the incident, the brigands split the reward money,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "the manor’s assets were sold off by the Dross family’s relatives,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and the two children were sent to different orphanages.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The police’s investigation was repeatedly hindered, and the case was finally classified as unsolved.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "It turned out that all of this was shrouded in a premeditated murder plot.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "By the time I uncovered these clues,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "my biological parents had already been dead for years,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and the moneylender from back then was serving time in prison for other crimes.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Count Barriere was an unscrupulous speculator—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "he was wherever there was profit to be made.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "He had also invested in Dr. Lamb’s Mediterranean project,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "buying Mediterranean development bonds.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Later, he seemed to take a fancy to some trait of mine,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and made a deal with me:", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "he lent me the bonds.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Along with the bonds,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "he also gave me a copy of Orfeo—perhaps it was a hint of something.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "In any case, this deal allowed me, who was not yet wealthy at the time, to directly obtain a share of the Mediterranean project’s profits.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "It was an extremely valuable deal.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Going back to the drug research—it was not smooth sailing.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Many raw materials were hard to obtain, transportation cycles were long, partners were unstable, and cultivation conditions were harsh.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "All these factors led to endless delays in the research.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "This was not the outcome I had hoped for.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My sister was still suffering,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and I couldn’t make her wait any longer.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "To control the schedule and ensure the drug could be put into use as soon as possible,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I had to take matters into my own hands in many processes.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "At that time, Oletus Manor was still under Manus’s control.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The suicide of his wife, Mary Kreiburg, at the racetrack was causing a huge stir.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The Kreiburg Racetrack was henceforth shrouded in an ominous aura.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Yet the horse races continued.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I took advantage of the turmoil during that period.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "My primary goal was, of course, to drive Manus out of the manor.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Naturally, I also had a hint of revenge in mind for that old debt.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I set my sights on the horse race held at Kreiburg Racetrack by Count Barriere to promote Simon Barriere, a rising star in horse racing from his family.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I staged a small \"accident\":", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "the famous horse Sernus went mad during the race, ran off the track, and caused a large-scale stampede with casualties.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The chaos it caused also made Simon, the jockey present at the time, fall off his horse and become permanently paralyzed.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Manus, in turn, was plunged into a crisis of huge debts.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "On one hand, Manus couldn’t get over his wife’s death;", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "on the other hand, he faced insurmountable debts.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "As expected, he went insane and disappeared without a trace.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The manor was once again put up for sale by its creditors.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "In 1898, the first phase of the drug research was completed,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and it was ready for the second phase of clinical trials.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I also obtained a large sum of money through the secret deals I had made earlier.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The time was ripe—", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "it was time to return to the manor.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I bought Oletus Manor under an alias,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "taking on the title of Baron Dross.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I also bought back the collectibles that had been sold off by the Dross relatives back then.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Bane and Balke were still here.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Finally, the old friends had returned.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I had reclaimed everything.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Oletus Manor was coming back to life again, just like the childhood memories of that time.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "In the same year, the novel I published became an overnight hit.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "I earned a generous royalty and a prestigious reputation.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "After I became famous, I immediately used the advantages of my wealth and fame to make connections,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "laying the groundwork for the endless stream of participants in the manor games to come.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "At the same time, I also had a group of trusted associates.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "The butler, Roy, and others would collect information on the participants for me and help arrange the experiment details,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "supporting the smooth progress of each experiment.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "None of this was one-sided persecution.", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "In fact, I only treated the participants with \"medicines tailored to their conditions.\"", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "Only by finding the most suitable drug", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "could I cure Alice’s mental anguish,", sprite: "characters/4.2.png", side: "left" },
                { name: "Orpheus Blanche", text: "and bring back my only remaining family member.", sprite: "characters/4.2.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};
