function getScenarioConfig() {
    return {
        meta: {
            title: "第一章第三幕",
            author: "第五人格团队"
        },
        assets: {
            background: "backgrounds/scene1.3.png",
            bgmusic: "audio/scene1.mp3"
        },
        uiText: {
            zh: { languageBtn: "中文", endText: "【剧情结束】", nextTip: "按空格键进入下一句" },
            en: { languageBtn: "English", endText: "[The End]", nextTip: "Press Space to continue"}
        },
        dialogues: {
            zh: [
                { name: "弗雷德・莱利", text: "我是弗雷德・莱利", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "一名律师", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "是，就是我卷走了里奥・贝克的财产", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我毁了他的工厂", sprite: "characters/1.3", side: "left" },
                { name: "弗雷德・莱利", text: "但是请问我做错什么了", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "合同是他签的", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "决定是他做的", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "程序是合法的", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "公平——", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "这是一个黑白不分混乱野蛮的时代", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "机器的轰鸣声震动了整条运河", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "多少的工人死于了工厂的尘肺病啊", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "这件事情公平吗", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "工厂从来没有给这些工人任何的补偿过", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "如果有人告工人们就会赢", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "但从来没有人代理过这些案子", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "因为没有任何一个工人能请得起律师", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "他们甚至不知道这件事情还可以付诸法律", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "这些公平吗", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我为了完成我在法学院的学业背上了需要 12 年才能还清的贷款", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我想说的是——", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "但这些都是合法的", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "包括我所做的一切的一切", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我只是善于利用我的谎言", sprite: "characters/1.3.png", side: "" },
                { name: "弗雷德・莱利", text: "来带来我想要的一切", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "让我摆脱那场失败的官司卑微的工作以及微薄到可笑的薪水", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我将获得金钱和财富", sprite:"characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "以及让我为之痴狂不惜一切代价的爱", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "只要这些都是合法的", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "在法律面前道德一无是处", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "但是现在我要去做一些违法的事情了", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我写好了遗嘱", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "分配了我所有的财产", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "只留下一间在密涅瓦附近的公寓", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "作为寻找莉迪亚・琼斯的抵偿悬赏", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "就是这个邪恶的女人在手术途中抛下了玛莎", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "害我失去了妻子和女儿", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我还收到了那座庄园的邀请函", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "里面提到了那个女人", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我当然要去", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我要让她付出代价", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "哪怕我自己也身败名裂粉身碎骨", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "哪怕我深知自己此去有去无回", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "玛莎...", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我当然知道...", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我当然知道我跟玛莎的爱会给我带来什么样的结局", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "可是当我看见她的时候", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "所有的原则任何的想法都没有任何意义了", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我爱她", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我愿意为她做任何事情", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "如果此刻魔鬼就在我的身侧", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "那就让她把我的灵魂拿走好了", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "我只想用我这残破不堪的灵魂", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "换来同她的片刻缠绵", sprite: "characters/1.3.png", side: "left" },
                { name: "弗雷德・莱利", text: "玛莎，地狱见。", sprite: "characters/1.3.png", side: "left" }
            ],
            en: [
                { name: "Fred Riley", text: "I am Fred Riley.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "A lawyer.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Yes, it was me who embezzled Leo Beck’s property.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I ruined his factory.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "But tell me, what did I do wrong?", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "He signed the contract.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "He made the decision.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "The process was legal.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Fairness—", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "this is an era of chaos and brutality where right and wrong are blurred.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "The roar of machines shook the entire canal.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "How many workers died from silicosis caused by the factory?", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Is that fair?", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "The factory never gave these workers any compensation.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "If someone had sued, the workers would have won.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "But no one ever took their cases.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Because not a single worker could afford a lawyer.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "They didn’t even know they could take this to court.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Is that fair?", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I took out a loan that would take 12 years to pay off just to finish my studies in law school.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "What I’m trying to say is—", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "but all of this was legal.", sprite: "characters/1.3.png", side: "" },
                { name: "Fred Riley", text: "Including everything I did.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I’m just good at using my lies", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "to get everything I want.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "To free myself from that losing lawsuit, that menial job, and that laughably meager salary.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I will gain money and wealth,", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "and the lover I’m obsessed with—someone I’d sacrifice anything for.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "As long as it’s all legal.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Morality means nothing in the face of the law.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "But now, I’m going to do something illegal.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I’ve written my will,", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "divided up all my assets.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I only kept an apartment near Minerva—", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "as a reward for anyone who finds Lydia Jones.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "It was that evil woman who abandoned Martha in the middle of surgery,", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "making me lose my wife and daughter.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I also received an invitation to that manor.", sprite: "characters/.png", side: "left" },
                { name: "Fred Riley", text: "It mentioned that woman.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Of course I’m going.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I want her to pay for what she did.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Even if I ruin my reputation and end up in pieces.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Even if I know full well I’ll never come back.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Martha...", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Of course I know...", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Of course I know what kind of end my love for Martha will bring me.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "But when I look at her,", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "all principles and all thoughts become meaningless.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I love her.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "I’d do anything for her.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "If the devil were by my side right now,", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "then let her take my soul.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "All I want is to trade my tattered soul", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "for a moment of intimacy with her.", sprite: "characters/1.3.png", side: "left" },
                { name: "Fred Riley", text: "Martha, see you in hell.", sprite: "characters/1.3.png", side: "left" }
            ]
        }
    };
}

window.scenarioConfig = {
    getScenarioConfig
};