// pages/Profile/profile.js
window.PROFILE_CHARACTERS = [
  {
    id: 'char1',
    name: '艾米丽·黛儿/莉迪娅·琼斯',
    img: 'photos/char1.png',
    birth: '3月17日',
    age: '32',
    skill: '医疗',
    hobby: '药草',
    like: '药草，书',
    dislike: '郊狼',
    trait: '冷静，敏感，胆怯，同情他人',
    job: '医生'
  },
  {
    id: 'char2',
    name: '艾玛·伍兹/丽莎·贝克',
    img: 'photos/char2.png',
    birth: '12月21日',
    age: '22',
    skill: '园艺，维修',
    hobby: '园艺，手工',
    like: '金丝雀',
    dislike: '老鼠，狐狸',
    trait: '善良，温和，细心，有行动力',
    job: '园丁'
  },
  {
    id: 'char3',
    name: '弗雷迪·莱利',
    img: 'photos/char3.png',
    birth: '1月12日',
    age: '38',
    skill: '写作，谈判',
    hobby: '阅读，写作',
    like: '玛莎，金钱',
    dislike: '蟑螂',
    trait: '傲慢和讽刺，贪婪，沙文主义，言而无信',
    job: '律师'
  },
  {
    id: 'char4',
    name: '里奥·贝克',
    img: 'photos/char4.png',
    birth: '12月21日（纪念日）',
    age: '？？？',
    skill: '制皮',
    hobby: '手工',
    like: '家人',
    dislike: '老鼠，狐狸',
    trait: '愤怒，烧伤，执着',
    job: '厂长'
  },
  {
    id: 'char5',
    name: '玛格丽莎·泽莱/娜塔莉',
    img: 'photos/char5.png',
    birth: '6月9日',
    age: '23',
    skill: '舞蹈，杂技，模仿',
    hobby: '派对，购物',
    like: '珠宝，华服，箱包',
    dislike: '廉价工业品',
    trait: '虚荣，自私，挑剔，迷糊',
    job: '舞女'
  },
  {
    id: 'char6',
    name: '麦克·莫顿',
    img: 'photos/char6.png',
    birth: '6月1日',
    age: '22',
    skill: '火药调制，弹跳，杂耍',
    hobby: '走钢丝',
    like: '狮子，舞台灯',
    dislike: '暴力和粗鲁的家伙',
    trait: '伸手灵活，孩子气，狡黠，三心二意',
    job: '杂技演员'
  },
  {
    id: 'char7',
    name: '裘克',
    img: 'photos/char7.png',
    birth: '8月4日（纪念日）',
    age: '20',
    skill: '改装',
    hobby: '滑稽戏',
    like: '娜塔莉，电锯',
    dislike: '运动系的人，软弱的人',
    trait: '疯狂，幽默，喜怒无常',
    job: '小丑'
  },
  {
    id: 'char8',
    name: '穆罗·莫顿',
    img: 'photos/char8.png',
    birth: '4月30日',
    age: '45',
    skill: '骑术，采集',
    hobby: '动物，水果',
    like: '森林，安静的地方',
    dislike: '城市，喧嚣的地方',
    trait: '孩子气，神经质，恐惧人类',
    job: '野人'
  },
  {
    id: 'char9',
    name: '瓦尔莱塔',
    img: 'photos/char9.png',
    birth: '1月2日（纪念日）',
    age: '？？？',
    skill: '纺织',
    hobby: '滑稽戏',
    like: '玩偶，帐篷',
    dislike: '火焰，阳光',
    trait: '安静，嫉妒，耐心',
    job: '蜘蛛'
  },
  {
    id: 'char10',
    name: '爱丽丝·德罗斯',
    img: 'photos/char10.png',
    birth: '5月5日',
    age: '21',
    skill: '伪装',
    hobby: '音乐，表演',
    like: '松露蛋糕，希腊神话',
    dislike: '黑暗的环境，鸟类的叫声',
    trait: '坚韧，聪敏，强耐受力，强迫症',
    job: '记者'
  },
  {
    id: 'char11',
    name: '弗雷德里克·克雷伯格',
    img: 'photos/char11.png',
    birth: '5月21日',
    age: '26',
    skill: '音律，马术',
    hobby: '音乐，心理学，神秘学',
    like: '极端美学，天赋卓越的人',
    dislike: '庸碌的人，珍珠，秘密被他人知晓',
    trait: '高傲，敏感，偏执，尖刻',
    job: '作曲家'
  },
  {
    id: 'char12',
    name: '诺顿·坎贝尔',
    img: 'photos/char12.png',
    birth: '3月19日（纪念日）',
    age: '28',
    skill: '矿石评鉴，矿石提炼',
    hobby: '矿石收藏',
    like: '贵重金属，天然宝石',
    dislike: '漆黑封闭的环境',
    trait: '勤俭，执着，有心机',
    job: '愚人金'  // ← 【已替换为“愚人金”】（改动点）
  },
  {
    id: 'char13',
    name: '梅莉·普林尼',
    img: 'photos/char13.png',
    birth: '12月22日',
    age: '28',
    skill: '昆虫研究，户外定向',
    hobby: '养花',
    like: '蜂蜜，鲜花，帽子',
    dislike: '噪音，白色，镜子',
    trait: '细心，悲观主义，直接敏锐，沉默寡言',
    job: '昆虫学者'
  },
  {
    id: 'char14',
    name: '玛丽·安托瓦内特',
    img: 'photos/char14.png',
    birth: '11月2日（纪念日）',
    age: '？？？',
    skill: '竖琴，舞蹈',
    hobby: '珠宝，时装，音乐',
    like: '美丽的事物',
    dislike: '粗鲁的事物',
    trait: '骄纵，享乐，倔强',
    job: '红夫人'
  },
  {
    id: 'char15',
    name: '“回忆”',
    img: 'photos/char15.png',
    birth: '9月13日',
    age: '？？？',
    skill: '？？？',
    hobby: '音乐，表演',
    like: '松露蛋糕，希腊神话',
    dislike: '黑暗的环境，鸟类的叫声',
    trait: '温柔，乐天，粗心大意',
    job: '小女孩'
  },
  {
    id: 'char16',
    name: '“奥尔菲斯”',
    img: 'photos/char16.png',
    birth: '4月2日',
    age: '24',
    skill: '写作，道具制作',
    hobby: '演绎法，犯罪学',
    like: '鸟类',
    dislike: '嘈杂的环境',
    trait: '倨傲，敏感，忧郁',
    job: '小说家'
  },
  {
    id: 'char17',
    name: '“奥尔菲斯”',
    img: 'photos/char17.png',
    birth: '4月2日（纪念日）',
    age: '？？？',
    skill: '心理学，药理学',
    hobby: '宗教知识，催眠',
    like: '黑暗的环境',
    dislike: '鸟类的叫声',
    trait: '阴郁，疯狂，狡猾',
    job: '噩梦'
  }
];
